### PR TITLE
Add missing OTP applications

### PR DESCRIPTION
**Pull request by Awea**

### CODE REVIEW

**Comment by manukall** [comment]
thanks @Awea ! 

do we actually need the `xmerl` app? it should actually be in `feeder`s applications instead, right?

**Comment by Awea** [comment]
@manukall Oh. That's right feeder_ex is just a wrapper for feeder so I need to report this to feeder instead of here ^^ It doesn't make sense to deal with dependencies of the wrapped library in the wrapper.

**Comment by Awea** [comment]
@manukall 2f1ca7d8729e8efb94b05360007b4efa10c18b10 now I need to made a pull request to feeder :D

**Comment by manukall** [comment]
@Awea thanks!

**Comment by wtfleming** [comment]
I have a project that uses feeder_ex as a dependency. I'm trying to build a release with exrm, and it's complaining about the feeder application missing from feeder_ex.

Wasn't sure if I should open a new issue or add this as a comment here, but would it be possible to get a 0.0.3 with awea's commit released to hex? 0.0.2 at https://hex.pm/packages/feeder_ex doesn't seem to have it.

cheers!

**Comment by manukall** [comment]
@Awea, @wtfleming forgot about that, sorry. i just published 0.0.3 now.

**Comment by wtfleming** [comment]
thank you

**Comment by Awea** [comment]
@manukall Feeder is updated too with `xmerl` dependecy :)

**Pull request merged**
